all:
  children:
    DC01:
      hosts:
        CentOS:
          ansible_host: 10.10.20.40
        nx01:
          ansible_host: 10.0.0.1
    branch1:
      hosts:
        r1:
          ansible_host: 10.10.10.1
        sw1:
          ansible_host: 10.10.10.10
    branch2:
      hosts:
        r2:
          ansible_host: 10.10.2.2
        sw2:
          ansible_host: 10.10.2.20
    nexus_switches:
      hosts:
        nx01:
          ansible_host: 10.0.0.1
    none_location:
      hosts:
        ISE_EST_Local_Host:
          ansible_host: 127.0.0.1
    none_type:
      hosts:
        ISE_EST_Local_Host:
          ansible_host: 127.0.0.1
    routers:
      hosts:
        r1:
          ansible_host: 10.10.10.1
        r2:
          ansible_host: 10.10.2.2
    servers:
      hosts:
        CentOS:
          ansible_host: 10.10.20.40
    switches:
      hosts:
        sw1:
          ansible_host: 10.10.10.10
        sw2:
          ansible_host: 10.10.2.20
